In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
df = pd.read_csv("datasets/breast_cancer_dataset.csv")
df.head()

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean_compactness  mean_concavity  mean_concave_points  mean_symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean_fractal_dimension  ...  worst_texture  worst_perimeter  worst_area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst_smoothness  worst_compactness  worst_concavity  worst_concave_points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst_symmetry  worst_fractal_dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [3]:
## Independent and dependent features
X = df.drop(labels=['target'],axis=1)
y = df[['target']]

In [4]:
y

target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [5]:
# Define which columns should be should be scaled
# Here all are numerical columns 
numerical_cols = X.select_dtypes(exclude='object').columns
categorical_cols = X.select_dtypes(include='object').columns

In [6]:
numerical_cols

Index(['mean_radius', 'mean_texture', 'mean_perimeter', 'mean_area',
       'mean_smoothness', 'mean_compactness', 'mean_concavity',
       'mean_concave_points', 'mean_symmetry', 'mean_fractal_dimension',
       'radius_error', 'texture_error', 'perimeter_error', 'area_error',
       'smoothness_error', 'compactness_error', 'concavity_error',
       'concave_points_error', 'symmetry_error', 'fractal_dimension_error',
       'worst_radius', 'worst_texture', 'worst_perimeter', 'worst_area',
       'worst_smoothness', 'worst_compactness', 'worst_concavity',
       'worst_concave_points', 'worst_symmetry', 'worst_fractal_dimension'],
      dtype='object')

In [7]:
categorical_cols

Index([], dtype='object')

In [8]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [9]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('scaler',StandardScaler())
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])


In [10]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [11]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [12]:
X_train.head()

num_pipeline__mean_radius  num_pipeline__mean_texture  \
0                  -0.514808                    0.567441   
1                  -0.142863                   -0.857433   
2                  -0.439257                    1.066147   
3                  -0.006290                   -1.482539   
4                   0.077979                    1.760198   

   num_pipeline__mean_perimeter  num_pipeline__mean_area  \
0                     -0.513367                -0.548491   
1                     -0.193401                -0.228724   
2                     -0.447269                -0.459765   
3                     -0.081835                -0.108079   
4                      0.011629                -0.021402   

   num_pipeline__mean_smoothness  num_pipeline__mean_compactness  \
0                      -0.587763                       -0.167987   
1                      -0.123760                       -0.699325   
2                      -1.207146                       -0.529636   
3                      -0.205014                       -0.949233   
4                      -1.854327                       -0.964899   

   num_pipeline__mean_concavity  num_pipeline__mean_concave_points  \
0                     -0.346818                          -0.275538   
1                     -0.510786                          -0.279195   
2                     -0.419039                          -0.721883   
3                     -0.878775                          -0.539845   
4                     -0.664615                          -0.799974   

   num_pipeline__mean_symmetry  num_pipeline__mean_fractal_dimension  ...  \
0                     0.451361                              0.214754  ...   
1                    -0.333906                             -0.883122  ...   
2                    -1.082306                             -0.353367  ...   
3                    -1.602131                             -0.824096  ...   
4                    -0.370773                             -1.218092  ...   

   num_pipeline__worst_radius  num_pipeline__worst_texture  \
0                   -0.515238                     0.761286   
1                   -0.299791                    -1.073007   
2                   -0.437086                     0.891048   
3                   -0.156160                    -1.241218   
4                   -0.183619                     0.998383   

   num_pipeline__worst_perimeter  num_pipeline__worst_area  \
0                      -0.480478                 -0.547975   
1                      -0.399641                 -0.351758   
2                      -0.504576                 -0.458982   
3                      -0.268778                 -0.231716   
4                      -0.207769                 -0.259335   

   num_pipeline__worst_smoothness  num_pipeline__worst_compactness  \
0                       -0.081928                        -0.046620   
1                       -0.197625                        -0.802086   
2                       -0.424570                         0.592173   
3                       -0.184276                        -0.919402   
4                       -1.359046                        -0.693149   

   num_pipeline__worst_concavity  num_pipeline__worst_concave_points  \
0                      -0.139269                            0.106198   
1                      -0.570920                           -0.333239   
2                       0.568334                            0.067351   
3                      -1.051103                           -0.850992   
4                      -0.600144                           -0.901804   

   num_pipeline__worst_symmetry  num_pipeline__worst_fractal_dimension  
0                      0.130638                               0.508765  
1                     -0.629689                              -1.057710  
2                     -0.120511                               0.693257  
3                     -1.369373                              -0.731432  
4                     -

In [13]:
## Model Training

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [14]:
regression = LogisticRegression()
regression.fit(X_train,y_train)

LogisticRegression()

In [15]:
def evaluate_model(true, predicted):
    accuracy = accuracy_score(true, predicted)
    confusionmat = confusion_matrix(true, predicted)
    report = classification_report(true, predicted)
    return accuracy,confusionmat,report

In [16]:
y_pred = regression.predict(X_test)
accuracyy,confusionmatt,reportt = evaluate_model(y_test,y_pred)

In [17]:
print('Model Training Performance')
print("\nConfusion Matrix:\n",confusionmatt)
print("\nClassification Report: \n\n",reportt)
print("\nAccuracy:",accuracyy)

Model Training Performance

Confusion Matrix:
 [[53  2]
 [ 1 87]]

Classification Report: 

               precision    recall  f1-score   support

           0       0.98      0.96      0.97        55
           1       0.98      0.99      0.98        88

    accuracy                           0.98       143
   macro avg       0.98      0.98      0.98       143
weighted avg       0.98      0.98      0.98       143


Accuracy: 0.9790209790209791


In [18]:
models={
    "Logistic Regression": LogisticRegression(),
    "Support Vector Machine": SVC(kernel='linear'),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Neural Network (MLP)": MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42)
}
trained_model_list=[]
model_list=[]
accuracy_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    accuracy,confusionmat,report =evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    #print('Model Training Performance')
    print("\nConfusion Matrix:\n",confusionmat)
    print("\nClassification Report: \n\n",report)
    print("\nAccuracy:",accuracy*100)

    accuracy_list.append(accuracy)
    
    print('='*35)


Logistic Regression

Confusion Matrix:
 [[53  2]
 [ 1 87]]

Classification Report: 

               precision    recall  f1-score   support

           0       0.98      0.96      0.97        55
           1       0.98      0.99      0.98        88

    accuracy                           0.98       143
   macro avg       0.98      0.98      0.98       143
weighted avg       0.98      0.98      0.98       143


Accuracy: 97.9020979020979
Support Vector Machine

Confusion Matrix:
 [[53  2]
 [ 1 87]]

Classification Report: 

               precision    recall  f1-score   support

           0       0.98      0.96      0.97        55
           1       0.98      0.99      0.98        88

    accuracy                           0.98       143
   macro avg       0.98      0.98      0.98       143
weighted avg       0.98      0.98      0.98       143


Accuracy: 97.9020979020979
Naive Bayes

Confusion Matrix:
 [[54  1]
 [ 3 85]]

Classification Report: 

               precision    recall  f1

In [19]:
my_dict = dict(zip(model_list, accuracy_list))
my_dict

{'Logistic Regression': 0.9790209790209791,
 'Support Vector Machine': 0.9790209790209791,
 'Naive Bayes': 0.972027972027972,
 'Random Forest': 0.951048951048951,
 'Gradient Boosting': 0.9790209790209791,
 'Decision Tree': 0.958041958041958,
 'Neural Network (MLP)': 0.9790209790209791}

In [20]:
'''
import pickle

# Find the index of the model with the highest R-squared score
best_model_index = accuracy_list.index(max(accuracy_list))

# Get the best model from the list of trained models
best_model = list(models.values())[best_model_index]

# Save the best model to a file using pickle
with open('bestt_model.pkl', 'wb') as model_file:
    pickle.dump(best_model, model_file)

# Loading the best model
with open('bestt_model.pkl', 'rb') as model_file:
    loaded_model = pickle.load(model_file) 

'''
print()

In [21]:
# Create a dictionary of classifiers and their respective hyperparameter grids for tuning
classifiers = {
    "Logistic Regression": {
        "model": LogisticRegression(),
        "params": {
            "penalty": ["l1", "l2"],
            "C": [0.01, 0.1, 1, 10]
        }
    },
    "Support Vector Machine": {
        "model": SVC(),
        "params": {
            "C": [0.1, 1, 10],
            "kernel": ["linear", "rbf"]
        }
    },
    "Naive Bayes": {
        "model": GaussianNB(),
        "params": {}
    },
    "Random Forest": {
        "model": RandomForestClassifier(),
        "params": {
            "n_estimators": [50, 100, 200],
            "max_depth": [None, 10, 20],
            "min_samples_split": [2, 5, 10],
            "min_samples_leaf": [1, 2, 4]
        }
    },
    "Gradient Boosting": {
        "model": GradientBoostingClassifier(),
        "params": {
            "n_estimators": [50, 100, 200],
            "learning_rate": [0.01, 0.1, 0.2],
            "max_depth": [3, 4, 5]
        }
    },
    "Decision Tree": {
        "model": DecisionTreeClassifier(),
        "params": {
            "max_depth": [None, 10, 20],
            "min_samples_split": [2, 5, 10],
            "min_samples_leaf": [1, 2, 4]
        }
    },
    "Neural Network (MLP)": {
        "model": MLPClassifier(),
        "params": {
            "hidden_layer_sizes": [(50, 50), (100, 50), (100, 100)],
            "alpha": [0.0001, 0.001, 0.01],
            "max_iter": [1000]
        }
    }
}

In [22]:
from sklearn.model_selection import GridSearchCV
best_params_list = []
# Perform hyperparameter tuning and evaluation for each classifier
for name, clf_info in classifiers.items():
    model = clf_info["model"]
    params = clf_info["params"]

    grid_search = GridSearchCV(model, params, cv=5, scoring='accuracy')
    grid_search.fit(X_train, y_train)

    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_

    # Make predictions with the best model
    y_pred = best_model.predict(X_test)

    # Evaluate the model and store results
    accuracy, confusionmat, report = evaluate_model(y_test, y_pred)
    
    # Append best params and accuracy to lists
    best_params_list.append((name, best_params))
    accuracy_list.append((name, accuracy))

    print(f"Classifier: {name}")
    print(f"Best Parameters: {best_params}")
    print(f"Accuracy: {accuracy}")
    print("Classification Report:")
    print(report)
    print("=" * 50)

Classifier: Logistic Regression
Best Parameters: {'C': 0.1, 'penalty': 'l2'}
Accuracy: 0.993006993006993
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        55
           1       0.99      1.00      0.99        88

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143

Classifier: Support Vector Machine
Best Parameters: {'C': 0.1, 'kernel': 'linear'}
Accuracy: 0.986013986013986
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        55
           1       0.99      0.99      0.99        88

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143

Classifier: Naive Bayes
Best Parameters: {}
Accuracy: 0.972027972027972
Classificati

In [23]:
# Print the best parameters and accuracy for each classifier
print("Best Parameters for Each Classifier:")
for name, best_params in best_params_list:
    print(f"Classifier: {name}")
    print(f"Best Parameters: {best_params}")
    print("=" * 50)


Best Parameters for Each Classifier:
Classifier: Logistic Regression
Best Parameters: {'C': 0.1, 'penalty': 'l2'}
Classifier: Support Vector Machine
Best Parameters: {'C': 0.1, 'kernel': 'linear'}
Classifier: Naive Bayes
Best Parameters: {}
Classifier: Random Forest
Best Parameters: {'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 50}
Classifier: Gradient Boosting
Best Parameters: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 50}
Classifier: Decision Tree
Best Parameters: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 5}
Classifier: Neural Network (MLP)
Best Parameters: {'alpha': 0.01, 'hidden_layer_sizes': (100, 100), 'max_iter': 1000}
